version: '3'

services:
  players:
    build: ./player
    ports:
    - 5002:80
    volumes:
      - ./player:/app
  site:
    build: ./site
    ports:
    - 5000:80
    depends_on:
    - players
    volumes:
      - ./site:/src

  