name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: continuos integration
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --t respect/continuous_docker_image
